if: tag IS blank
sudo: false

language: scala
scala:
  - 2.12.10
jdk:
  - openjdk8


before_install:
  - openssl aes-256-cbc -K $encrypted_4746dfea8a51_key -iv $encrypted_4746dfea8a51_iv -in .travis/secret-key.asc.enc -out .travis/secret-key.asc -d
  - echo $PGP_PASSPHRASE | gpg --passphrase-fd 0 --batch --yes --import .travis/secret-key.asc

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script: sbt ++$TRAVIS_SCALA_VERSION scalafmtSbtCheck scalafmtCheckAll scripted

deploy:
  - provider: script
    script: ".travis/deploy.sh"
    skip_cleanup: true
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH =~ ^master|develop$"
